2022-02-17T08:57:57.6110588+07:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2022-02-17T08:57:57.6189463+07:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2022-02-17T08:57:57.6208130+07:00  [INF] Hosting environment: "Development" (c3307c92)
2022-02-17T08:57:57.6223481+07:00  [INF] Content root path: "E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC" (b5d60022)
2022-02-17T08:57:59.2062935+07:00 0HMFHN3LPSDGM:00000001 [WRN] Failed to determine the https port for redirect. (ca76cc21)
2022-02-17T08:58:11.4118499+07:00 0HMFHN3LPSDGR:00000004 [INF] User logged in. (fdce0db4)
2022-02-17T09:28:42.7614768+07:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2022-02-17T09:28:42.7692566+07:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2022-02-17T09:28:42.7707718+07:00  [INF] Hosting environment: "Development" (c3307c92)
2022-02-17T09:28:42.7979996+07:00  [INF] Content root path: "E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC" (b5d60022)
2022-02-17T09:28:44.1018155+07:00 0HMFHNKRLJOA5:00000001 [WRN] Failed to determine the https port for redirect. (ca76cc21)
2022-02-17T09:28:49.1342976+07:00 0HMFHNKRLJOA9:00000004 [INF] User logged in. (fdce0db4)
2022-02-17T09:31:10.0533003+07:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2022-02-17T09:31:10.0607936+07:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2022-02-17T09:31:10.0623539+07:00  [INF] Hosting environment: "Development" (c3307c92)
2022-02-17T09:31:10.0634450+07:00  [INF] Content root path: "E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC" (b5d60022)
2022-02-17T09:31:11.5236297+07:00 0HMFHNM7IUSAJ:00000001 [WRN] Failed to determine the https port for redirect. (ca76cc21)
2022-02-17T09:31:16.1792268+07:00 0HMFHNM7IUSAO:00000004 [INF] User logged in. (fdce0db4)
2022-02-17T09:35:46.9734371+07:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2022-02-17T09:35:46.9834667+07:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2022-02-17T09:35:46.9852191+07:00  [INF] Hosting environment: "Development" (c3307c92)
2022-02-17T09:35:46.9864855+07:00  [INF] Content root path: "E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC" (b5d60022)
2022-02-17T09:35:48.2088957+07:00 0HMFHNOQ3CNR2:00000001 [WRN] Failed to determine the https port for redirect. (ca76cc21)
2022-02-17T09:35:53.8737459+07:00 0HMFHNOQ3CNR5:00000005 [INF] User logged in. (fdce0db4)
2022-02-17T09:56:55.8818650+07:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2022-02-17T09:56:55.8898930+07:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2022-02-17T09:56:55.8914611+07:00  [INF] Hosting environment: "Development" (c3307c92)
2022-02-17T09:56:55.8924261+07:00  [INF] Content root path: "E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC" (b5d60022)
2022-02-17T09:56:57.3266844+07:00 0HMFHO4K9A0I8:00000001 [WRN] Failed to determine the https port for redirect. (ca76cc21)
2022-02-17T09:57:01.8618597+07:00 0HMFHO4K9A0IC:00000004 [INF] User logged in. (fdce0db4)
2022-02-17T10:04:22.8648608+07:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2022-02-17T10:04:22.8724121+07:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2022-02-17T10:04:22.8741650+07:00  [INF] Hosting environment: "Development" (c3307c92)
2022-02-17T10:04:22.8753763+07:00  [INF] Content root path: "E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC" (b5d60022)
2022-02-17T10:04:24.0589080+07:00 0HMFHO8PFONUU:00000001 [WRN] Failed to determine the https port for redirect. (ca76cc21)
2022-02-17T10:04:44.2941454+07:00 0HMFHO8PFONV1:00000004 [INF] User logged in. (fdce0db4)
2022-02-17T10:19:40.5351373+07:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2022-02-17T10:19:40.5429645+07:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2022-02-17T10:19:40.5443709+07:00  [INF] Hosting environment: "Development" (c3307c92)
2022-02-17T10:19:40.5455612+07:00  [INF] Content root path: "E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC" (b5d60022)
2022-02-17T10:19:42.0079321+07:00 0HMFHOHB155MB:00000001 [WRN] Failed to determine the https port for redirect. (ca76cc21)
2022-02-17T10:19:46.5515762+07:00 0HMFHOHB155MF:00000003 [INF] User logged in. (fdce0db4)
2022-02-17T10:26:17.8951723+07:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2022-02-17T10:26:17.9028738+07:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2022-02-17T10:26:17.9046592+07:00  [INF] Hosting environment: "Development" (c3307c92)
2022-02-17T10:26:17.9057911+07:00  [INF] Content root path: "E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC" (b5d60022)
2022-02-17T10:26:19.0160773+07:00 0HMFHOL1AVRFH:00000001 [WRN] Failed to determine the https port for redirect. (ca76cc21)
2022-02-17T10:26:28.9612402+07:00 0HMFHOL1AVRFI:00000004 [INF] User logged in. (fdce0db4)
2022-02-17T10:38:44.3195571+07:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2022-02-17T10:38:44.3301324+07:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2022-02-17T10:38:44.3320270+07:00  [INF] Hosting environment: "Development" (c3307c92)
2022-02-17T10:38:44.3336337+07:00  [INF] Content root path: "E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC" (b5d60022)
2022-02-17T10:38:45.8453382+07:00 0HMFHORVSSI7J:00000001 [WRN] Failed to determine the https port for redirect. (ca76cc21)
2022-02-17T10:38:51.2430947+07:00 0HMFHORVSSI7O:00000004 [INF] User logged in. (fdce0db4)
2022-02-17T10:51:03.7107566+07:00 0HMFHORVSSI7P:00000002 [ERR] An error occurred using the connection to database '"HRMSDB"' on server '"10.70.10.97"'. (5fc3407c)
2022-02-17T10:51:03.8659302+07:00 0HMFHORVSSI7P:00000002 [ERR] An exception occurred while iterating over the results of a query for context type '"VOC.Data.EF.AppDBContext"'."
""System.InvalidOperationException: An exception has been raised that is likely due to a transient failure. Consider enabling transient error resiliency by adding 'EnableRetryOnFailure()' to the 'UseSqlServer' call.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 0 - The specified network name is no longer available.)
 ---> System.ComponentModel.Win32Exception (64): The specified network name is no longer available.
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParserStateObject.ThrowExceptionAndWarning(Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParserStateObject.ReadSniError(TdsParserStateObject stateObj, UInt32 error)
   at Microsoft.Data.SqlClient.TdsParserStateObject.ReadSniSyncOverAsync()
   at Microsoft.Data.SqlClient.TdsParserStateObject.TryReadNetworkPacket()
   at Microsoft.Data.SqlClient.TdsParser.ConsumePreLoginHandshake(Boolean encrypt, Boolean trustServerCert, Boolean integratedSecurity, Boolean& marsCapable, Boolean& fedAuthRequired)
   at Microsoft.Data.SqlClient.TdsParser.Connect(ServerInfo serverInfo, SqlInternalConnectionTds connHandler, Boolean ignoreSniOpenTimeout, Int64 timerExpire, Boolean encrypt, Boolean trustServerCert, Boolean integratedSecurity, Boolean withFailover, SqlAuthenticationMethod authType, SqlAuthenticationProviderManager sqlAuthProviderManager)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool, SqlAuthenticationProviderManager sqlAuthProviderManager)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at Microsoft.Data.SqlClient.SqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
ClientConnectionId:74c6bd0c-935c-43ce-998d-c2b11fea99e2
Error Number:64,State:0,Class:20
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()" (f5c7ac34)
System.InvalidOperationException: An exception has been raised that is likely due to a transient failure. Consider enabling transient error resiliency by adding 'EnableRetryOnFailure()' to the 'UseSqlServer' call.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 0 - The specified network name is no longer available.)
 ---> System.ComponentModel.Win32Exception (64): The specified network name is no longer available.
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParserStateObject.ThrowExceptionAndWarning(Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParserStateObject.ReadSniError(TdsParserStateObject stateObj, UInt32 error)
   at Microsoft.Data.SqlClient.TdsParserStateObject.ReadSniSyncOverAsync()
   at Microsoft.Data.SqlClient.TdsParserStateObject.TryReadNetworkPacket()
   at Microsoft.Data.SqlClient.TdsParser.ConsumePreLoginHandshake(Boolean encrypt, Boolean trustServerCert, Boolean integratedSecurity, Boolean& marsCapable, Boolean& fedAuthRequired)
   at Microsoft.Data.SqlClient.TdsParser.Connect(ServerInfo serverInfo, SqlInternalConnectionTds connHandler, Boolean ignoreSniOpenTimeout, Int64 timerExpire, Boolean encrypt, Boolean trustServerCert, Boolean integratedSecurity, Boolean withFailover, SqlAuthenticationMethod authType, SqlAuthenticationProviderManager sqlAuthProviderManager)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool, SqlAuthenticationProviderManager sqlAuthProviderManager)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at Microsoft.Data.SqlClient.SqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
ClientConnectionId:74c6bd0c-935c-43ce-998d-c2b11fea99e2
Error Number:64,State:0,Class:20
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
2022-02-17T10:51:04.2252832+07:00 0HMFHORVSSI7P:00000002 [ERR] An exception occurred while calculating the database error page content. Skipping display of the database error page. (3f43c218)
System.InvalidOperationException: An exception has been raised that is likely due to a transient failure. Consider enabling transient error resiliency by adding 'EnableRetryOnFailure()' to the 'UseSqlServer' call.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 0 - The specified network name is no longer available.)
 ---> System.ComponentModel.Win32Exception (64): The specified network name is no longer available.
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at Microsoft.Data.SqlClient.SqlConnection.OpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.<>c__DisplayClass20_0.<<ExistsAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.<>c__DisplayClass20_0.<<ExistsAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.<>c__DisplayClass20_0.<<ExistsAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
ClientConnectionId:74c6bd0c-935c-43ce-998d-c2b11fea99e2
Error Number:64,State:0,Class:20
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
2022-02-17T10:51:04.2971177+07:00 0HMFHORVSSI7P:00000002 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.InvalidOperationException: An exception has been raised that is likely due to a transient failure. Consider enabling transient error resiliency by adding 'EnableRetryOnFailure()' to the 'UseSqlServer' call.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 0 - The specified network name is no longer available.)
 ---> System.ComponentModel.Win32Exception (64): The specified network name is no longer available.
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParserStateObject.ThrowExceptionAndWarning(Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParserStateObject.ReadSniError(TdsParserStateObject stateObj, UInt32 error)
   at Microsoft.Data.SqlClient.TdsParserStateObject.ReadSniSyncOverAsync()
   at Microsoft.Data.SqlClient.TdsParserStateObject.TryReadNetworkPacket()
   at Microsoft.Data.SqlClient.TdsParser.ConsumePreLoginHandshake(Boolean encrypt, Boolean trustServerCert, Boolean integratedSecurity, Boolean& marsCapable, Boolean& fedAuthRequired)
   at Microsoft.Data.SqlClient.TdsParser.Connect(ServerInfo serverInfo, SqlInternalConnectionTds connHandler, Boolean ignoreSniOpenTimeout, Int64 timerExpire, Boolean encrypt, Boolean trustServerCert, Boolean integratedSecurity, Boolean withFailover, SqlAuthenticationMethod authType, SqlAuthenticationProviderManager sqlAuthProviderManager)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool, SqlAuthenticationProviderManager sqlAuthProviderManager)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at Microsoft.Data.SqlClient.SqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
ClientConnectionId:74c6bd0c-935c-43ce-998d-c2b11fea99e2
Error Number:64,State:0,Class:20
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at VOC.Application.Implementation.QuatrinhLamViecService.GetAll(String keyword) in E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC.Application\Implementation\QuatrinhLamViecService.cs:line 57
   at VOC.Areas.Admin.Controllers.NhanVienController.UpdateQuatrinhCtac(List`1 lstQtrinhCtac, String id) in E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC\Areas\Admin\Controllers\NhanVienController.cs:line 710
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2022-02-17T10:54:34.2025280+07:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2022-02-17T10:54:34.2100472+07:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2022-02-17T10:54:34.2114600+07:00  [INF] Hosting environment: "Development" (c3307c92)
2022-02-17T10:54:34.2127871+07:00  [INF] Content root path: "E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC" (b5d60022)
2022-02-17T10:54:35.2786374+07:00 0HMFHP4QS4926:00000001 [WRN] Failed to determine the https port for redirect. (ca76cc21)
2022-02-17T10:54:41.0400027+07:00 0HMFHP4QS4929:00000004 [INF] User logged in. (fdce0db4)
2022-02-17T11:10:34.6812052+07:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2022-02-17T11:10:34.6892294+07:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2022-02-17T11:10:34.6908769+07:00  [INF] Hosting environment: "Development" (c3307c92)
2022-02-17T11:10:34.7187083+07:00  [INF] Content root path: "E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC" (b5d60022)
2022-02-17T11:10:36.0888417+07:00 0HMFHPDP5PVFM:00000001 [WRN] Failed to determine the https port for redirect. (ca76cc21)
2022-02-17T11:10:40.0627627+07:00 0HMFHPDP5PVFO:00000004 [INF] User logged in. (fdce0db4)
2022-02-17T11:12:01.5991043+07:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2022-02-17T11:12:01.6075739+07:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2022-02-17T11:12:01.6091042+07:00  [INF] Hosting environment: "Development" (c3307c92)
2022-02-17T11:12:01.6101116+07:00  [INF] Content root path: "E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC" (b5d60022)
2022-02-17T11:12:02.9552544+07:00 0HMFHPEJ4B0QE:00000001 [WRN] Failed to determine the https port for redirect. (ca76cc21)
2022-02-17T11:12:08.2373487+07:00 0HMFHPEJ4B0QG:00000004 [INF] User logged in. (fdce0db4)
2022-02-17T11:13:37.4961907+07:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2022-02-17T11:13:37.5056019+07:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2022-02-17T11:13:37.5071461+07:00  [INF] Hosting environment: "Development" (c3307c92)
2022-02-17T11:13:37.5083984+07:00  [INF] Content root path: "E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC" (b5d60022)
2022-02-17T11:13:38.9674524+07:00 0HMFHPFFN8JGQ:00000001 [WRN] Failed to determine the https port for redirect. (ca76cc21)
2022-02-17T11:13:43.2766416+07:00 0HMFHPFFN8JGR:00000005 [INF] User logged in. (fdce0db4)
2022-02-17T11:15:31.5398646+07:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2022-02-17T11:15:31.5483646+07:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2022-02-17T11:15:31.5499724+07:00  [INF] Hosting environment: "Development" (c3307c92)
2022-02-17T11:15:31.5515943+07:00  [INF] Content root path: "E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC" (b5d60022)
2022-02-17T11:15:32.7421998+07:00 0HMFHPGHK8VSQ:00000001 [WRN] Failed to determine the https port for redirect. (ca76cc21)
2022-02-17T11:15:37.4692119+07:00 0HMFHPGHK8VSS:00000005 [INF] User logged in. (fdce0db4)
2022-02-17T11:16:18.6435068+07:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2022-02-17T11:16:18.6511700+07:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2022-02-17T11:16:18.6526901+07:00  [INF] Hosting environment: "Development" (c3307c92)
2022-02-17T11:16:18.6822776+07:00  [INF] Content root path: "E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC" (b5d60022)
2022-02-17T11:16:20.0179706+07:00 0HMFHPGVNQME0:00000001 [WRN] Failed to determine the https port for redirect. (ca76cc21)
2022-02-17T11:16:24.2900085+07:00 0HMFHPGVNQME4:00000004 [INF] User logged in. (fdce0db4)
2022-02-17T11:28:44.9486426+07:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2022-02-17T11:28:44.9574610+07:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2022-02-17T11:28:44.9588588+07:00  [INF] Hosting environment: "Development" (c3307c92)
2022-02-17T11:28:44.9604344+07:00  [INF] Content root path: "E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC" (b5d60022)
2022-02-17T11:28:46.1420260+07:00 0HMFHPNU1BTUT:00000001 [WRN] Failed to determine the https port for redirect. (ca76cc21)
2022-02-17T11:28:53.5848190+07:00 0HMFHPNU1BTUU:00000004 [INF] User logged in. (fdce0db4)
2022-02-17T11:38:20.8777373+07:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2022-02-17T11:38:20.8864822+07:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2022-02-17T11:38:20.8878724+07:00  [INF] Hosting environment: "Development" (c3307c92)
2022-02-17T11:38:20.8889489+07:00  [INF] Content root path: "E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC" (b5d60022)
2022-02-17T11:38:23.2476914+07:00 0HMFHPT9QBQ3Q:00000001 [WRN] Failed to determine the https port for redirect. (ca76cc21)
2022-02-17T11:38:27.6600683+07:00 0HMFHPT9QBQ3T:00000002 [INF] User logged in. (fdce0db4)
2022-02-17T11:39:39.4724681+07:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2022-02-17T11:39:39.4806294+07:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2022-02-17T11:39:39.4825470+07:00  [INF] Hosting environment: "Development" (c3307c92)
2022-02-17T11:39:39.4841062+07:00  [INF] Content root path: "E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC" (b5d60022)
2022-02-17T11:39:40.4766995+07:00 0HMFHPU13N7US:00000001 [WRN] Failed to determine the https port for redirect. (ca76cc21)
2022-02-17T11:39:47.4516249+07:00 0HMFHPU13N7UV:00000004 [INF] User logged in. (fdce0db4)
2022-02-17T11:43:08.6068916+07:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2022-02-17T11:43:08.6143006+07:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2022-02-17T11:43:08.6161855+07:00  [INF] Hosting environment: "Development" (c3307c92)
2022-02-17T11:43:08.6389772+07:00  [INF] Content root path: "E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC" (b5d60022)
2022-02-17T11:43:10.0002238+07:00 0HMFHPVVI9NA8:00000001 [WRN] Failed to determine the https port for redirect. (ca76cc21)
2022-02-17T11:43:14.2905781+07:00 0HMFHPVVI9NAD:00000004 [INF] User logged in. (fdce0db4)
2022-02-17T11:44:31.6613272+07:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2022-02-17T11:44:31.6709655+07:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2022-02-17T11:44:31.6727364+07:00  [INF] Hosting environment: "Development" (c3307c92)
2022-02-17T11:44:31.6746288+07:00  [INF] Content root path: "E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC" (b5d60022)
2022-02-17T11:44:32.8772447+07:00 0HMFHQ0O926DL:00000001 [WRN] Failed to determine the https port for redirect. (ca76cc21)
2022-02-17T11:44:37.3411756+07:00 0HMFHQ0O926DL:00000006 [INF] User logged in. (fdce0db4)
2022-02-17T11:49:18.5952383+07:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2022-02-17T11:49:18.6026330+07:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2022-02-17T11:49:18.6042130+07:00  [INF] Hosting environment: "Development" (c3307c92)
2022-02-17T11:49:18.6052405+07:00  [INF] Content root path: "E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC" (b5d60022)
2022-02-17T11:49:19.8215930+07:00 0HMFHQ3DPEDUT:00000001 [WRN] Failed to determine the https port for redirect. (ca76cc21)
2022-02-17T11:49:24.5062149+07:00 0HMFHQ3DPEDUV:00000004 [INF] User logged in. (fdce0db4)
2022-02-17T11:51:54.9531921+07:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2022-02-17T11:51:54.9611446+07:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2022-02-17T11:51:54.9624813+07:00  [INF] Hosting environment: "Development" (c3307c92)
2022-02-17T11:51:54.9636170+07:00  [INF] Content root path: "E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC" (b5d60022)
2022-02-17T11:51:55.8620361+07:00 0HMFHQ4S9JUV6:00000001 [WRN] Failed to determine the https port for redirect. (ca76cc21)
2022-02-17T11:52:01.0203968+07:00 0HMFHQ4S9JUV8:00000004 [INF] User logged in. (fdce0db4)
2022-02-17T11:59:38.4840772+07:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2022-02-17T11:59:38.4920970+07:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2022-02-17T11:59:38.4934066+07:00  [INF] Hosting environment: "Development" (c3307c92)
2022-02-17T11:59:38.4948102+07:00  [INF] Content root path: "E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC" (b5d60022)
2022-02-17T11:59:39.9413604+07:00 0HMFHQ96HJR7P:00000001 [WRN] Failed to determine the https port for redirect. (ca76cc21)
2022-02-17T11:59:45.0935332+07:00 0HMFHQ96HJR7R:00000005 [INF] User logged in. (fdce0db4)
2022-02-17T12:04:35.8514427+07:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2022-02-17T12:04:35.8590155+07:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2022-02-17T12:04:35.8610552+07:00  [INF] Hosting environment: "Development" (c3307c92)
2022-02-17T12:04:35.8626455+07:00  [INF] Content root path: "E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC" (b5d60022)
2022-02-17T12:04:37.0179539+07:00 0HMFHQBV406RL:00000001 [WRN] Failed to determine the https port for redirect. (ca76cc21)
2022-02-17T12:04:45.3136410+07:00 0HMFHQBV406RM:00000004 [INF] User logged in. (fdce0db4)
2022-02-17T12:07:00.9941383+07:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2022-02-17T12:07:01.0017904+07:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2022-02-17T12:07:01.0034434+07:00  [INF] Hosting environment: "Development" (c3307c92)
2022-02-17T12:07:01.0048236+07:00  [INF] Content root path: "E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC" (b5d60022)
2022-02-17T12:07:02.0388381+07:00 0HMFHQDAB6682:00000001 [WRN] Failed to determine the https port for redirect. (ca76cc21)
2022-02-17T12:07:06.6401361+07:00 0HMFHQDAB6685:00000004 [INF] User logged in. (fdce0db4)
2022-02-17T13:03:51.8257198+07:00 0HMFHQDAB668A:00000003 [ERR] An exception occurred while iterating over the results of a query for context type '"VOC.Data.EF.AppDBContext"'."
""Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot create a row of size 8938 which is greater than the allowable maximum row size of 8060.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
   at Microsoft.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
   at Microsoft.Data.SqlClient.SqlDataReader.Read()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
ClientConnectionId:73074d07-6453-4b03-be46-d38482e123a3
Error Number:511,State:1,Class:16" (f5c7ac34)
Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot create a row of size 8938 which is greater than the allowable maximum row size of 8060.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
   at Microsoft.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
   at Microsoft.Data.SqlClient.SqlDataReader.Read()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
ClientConnectionId:73074d07-6453-4b03-be46-d38482e123a3
Error Number:511,State:1,Class:16
2022-02-17T13:03:52.2168486+07:00 0HMFHQDAB668A:00000003 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot create a row of size 8938 which is greater than the allowable maximum row size of 8060.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
   at Microsoft.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
   at Microsoft.Data.SqlClient.SqlDataReader.Read()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at VOC.Application.Implementation.CheDoBHService.GetAll(String filter) in E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC.Application\Implementation\CheDoBHService.cs:line 41
   at VOC.Areas.Admin.Controllers.NhanVienController.Profile(String Id) in E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC\Areas\Admin\Controllers\NhanVienController.cs:line 429
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
ClientConnectionId:73074d07-6453-4b03-be46-d38482e123a3
Error Number:511,State:1,Class:16
2022-02-17T13:13:22.6660322+07:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2022-02-17T13:13:22.6739281+07:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2022-02-17T13:13:22.6756657+07:00  [INF] Hosting environment: "Development" (c3307c92)
2022-02-17T13:13:22.6769007+07:00  [INF] Content root path: "E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC" (b5d60022)
2022-02-17T13:13:23.6113453+07:00 0HMFHRICULGM0:00000001 [WRN] Failed to determine the https port for redirect. (ca76cc21)
2022-02-17T13:13:31.9033790+07:00 0HMFHRICULGM5:00000003 [INF] User logged in. (fdce0db4)
2022-02-17T13:13:32.6962969+07:00 0HMFHRICULGM5:00000004 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
AutoMapper.AutoMapperMappingException: Missing type map configuration or unsupported mapping.

Mapping types:
AsyncStateMachineBox`1 -> Task`1
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Collections.Generic.List`1[[VOC.Data.Entities.FUNCTION, VOC.Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions+<ToListAsync>d__64`1[[VOC.Data.Entities.FUNCTION, VOC.Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], Microsoft.EntityFrameworkCore, Version=3.1.16.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]] -> System.Threading.Tasks.Task`1[[System.Collections.Generic.List`1[[VOC.Application.ViewModels.System.FunctionViewModel, VOC.Application, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]
   at lambda_method(Closure , AsyncStateMachineBox`1 , Task`1 , ResolutionContext )
   at lambda_method(Closure , Object , Object , ResolutionContext )
   at VOC.Application.Implementation.FunctionService.GetAll(String filter) in E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC.Application\Implementation\FunctionService.cs:line 57
   at VOC.Areas.Admin.Components.SideBarViewComponent.InvokeAsync() in E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC\Areas\Admin\Components\SideBarViewComponent.cs:line 28
   at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentInvoker.InvokeAsyncCore(ObjectMethodExecutor executor, ViewComponentContext context)
   at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentInvoker.InvokeAsync(ViewComponentContext context)
   at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentHelper.InvokeCoreAsync(ViewComponentDescriptor descriptor, Object arguments)
   at AspNetCore.Areas_Admin_Views_Shared__Layout.<ExecuteAsync>b__64_1() in E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC\Areas\Admin\Views\Shared\_Layout.cshtml:line 236
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.SetOutputContentAsync()
   at AspNetCore.Areas_Admin_Views_Shared__Layout.ExecuteAsync()
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderLayoutAsync(ViewContext context, ViewBufferTextWriter bodyWriter)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2022-02-17T13:18:20.0154870+07:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2022-02-17T13:18:20.0228396+07:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2022-02-17T13:18:20.0244111+07:00  [INF] Hosting environment: "Development" (c3307c92)
2022-02-17T13:18:20.0260698+07:00  [INF] Content root path: "E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC" (b5d60022)
2022-02-17T13:18:21.3649275+07:00 0HMFHRL5LSA2S:00000001 [WRN] Failed to determine the https port for redirect. (ca76cc21)
2022-02-17T13:18:26.0718695+07:00 0HMFHRL5LSA2T:00000004 [INF] User logged in. (fdce0db4)
2022-02-17T13:18:26.7248152+07:00 0HMFHRL5LSA2T:00000005 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.InvalidOperationException: Method 'InvokeAsync' of view component 'VOC.Areas.Admin.Components.SideBarViewComponent' should be declared to return Task<T>.
   at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentDescriptorProvider.FindMethod(Type componentType)
   at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentDescriptorProvider.CreateDescriptor(TypeInfo typeInfo)
   at System.Linq.Enumerable.SelectListIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentDescriptorCollectionProvider.GetViewComponents()
   at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentDescriptorCollectionProvider.get_ViewComponents()
   at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentSelector.SelectComponent(String componentName)
   at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentHelper.InvokeAsync(String name, Object arguments)
   at Microsoft.AspNetCore.Mvc.Rendering.ViewComponentHelperExtensions.InvokeAsync(IViewComponentHelper helper, String name)
   at AspNetCore.Areas_Admin_Views_Shared__Layout.<ExecuteAsync>b__64_1() in E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC\Areas\Admin\Views\Shared\_Layout.cshtml:line 236
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.SetOutputContentAsync()
   at AspNetCore.Areas_Admin_Views_Shared__Layout.ExecuteAsync()
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderLayoutAsync(ViewContext context, ViewBufferTextWriter bodyWriter)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2022-02-17T13:20:07.0818145+07:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2022-02-17T13:20:07.0897336+07:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2022-02-17T13:20:07.0919721+07:00  [INF] Hosting environment: "Development" (c3307c92)
2022-02-17T13:20:07.0936105+07:00  [INF] Content root path: "E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC" (b5d60022)
2022-02-17T13:20:08.4539266+07:00 0HMFHRM5J475O:00000001 [WRN] Failed to determine the https port for redirect. (ca76cc21)
2022-02-17T13:20:12.5212885+07:00 0HMFHRM5J475S:00000004 [INF] User logged in. (fdce0db4)
2022-02-17T13:23:04.9895731+07:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2022-02-17T13:23:04.9970686+07:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2022-02-17T13:23:04.9988516+07:00  [INF] Hosting environment: "Development" (c3307c92)
2022-02-17T13:23:05.0001640+07:00  [INF] Content root path: "E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC" (b5d60022)
2022-02-17T13:23:05.9533607+07:00 0HMFHRNQGEBRC:00000001 [WRN] Failed to determine the https port for redirect. (ca76cc21)
2022-02-17T13:23:12.1843811+07:00 0HMFHRNQGEBRH:00000005 [INF] User logged in. (fdce0db4)
2022-02-17T13:25:28.4655270+07:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2022-02-17T13:25:28.4758231+07:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2022-02-17T13:25:28.4779665+07:00  [INF] Hosting environment: "Development" (c3307c92)
2022-02-17T13:25:28.4801439+07:00  [INF] Content root path: "E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC" (b5d60022)
2022-02-17T13:25:29.7683347+07:00 0HMFHRP5AIHB1:00000001 [WRN] Failed to determine the https port for redirect. (ca76cc21)
2022-02-17T13:25:35.7851338+07:00 0HMFHRP5AIHB6:00000005 [INF] User logged in. (fdce0db4)
2022-02-17T13:28:01.8525075+07:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2022-02-17T13:28:01.8605079+07:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2022-02-17T13:28:01.8624544+07:00  [INF] Hosting environment: "Development" (c3307c92)
2022-02-17T13:28:01.8641653+07:00  [INF] Content root path: "E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC" (b5d60022)
2022-02-17T13:28:03.2170363+07:00 0HMFHRQJ2O6L5:00000001 [WRN] Failed to determine the https port for redirect. (ca76cc21)
2022-02-17T13:28:09.7748824+07:00 0HMFHRQJ2O6LA:00000005 [INF] User logged in. (fdce0db4)
2022-02-17T13:31:26.6552051+07:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2022-02-17T13:31:26.6632008+07:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2022-02-17T13:31:26.6647924+07:00  [INF] Hosting environment: "Development" (c3307c92)
2022-02-17T13:31:26.6664496+07:00  [INF] Content root path: "E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC" (b5d60022)
2022-02-17T13:31:27.9765535+07:00 0HMFHRSG2P18G:00000001 [WRN] Failed to determine the https port for redirect. (ca76cc21)
2022-02-17T13:31:32.2459591+07:00 0HMFHRSG2P18K:00000004 [INF] User logged in. (fdce0db4)
2022-02-17T13:32:00.9080625+07:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2022-02-17T13:32:00.9156244+07:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2022-02-17T13:32:00.9170511+07:00  [INF] Hosting environment: "Development" (c3307c92)
2022-02-17T13:32:00.9446506+07:00  [INF] Content root path: "E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC" (b5d60022)
2022-02-17T13:32:02.1360793+07:00 0HMFHRSQ94D44:00000001 [WRN] Failed to determine the https port for redirect. (ca76cc21)
2022-02-17T13:32:05.9716834+07:00 0HMFHRSQ94D48:00000005 [INF] User logged in. (fdce0db4)
2022-02-17T13:36:53.0746244+07:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2022-02-17T13:36:53.0855292+07:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2022-02-17T13:36:53.0873309+07:00  [INF] Hosting environment: "Development" (c3307c92)
2022-02-17T13:36:53.0899414+07:00  [INF] Content root path: "E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC" (b5d60022)
2022-02-17T13:36:54.3792423+07:00 0HMFHRVHCTIFC:00000001 [WRN] Failed to determine the https port for redirect. (ca76cc21)
2022-02-17T13:37:00.0797311+07:00 0HMFHRVHCTIFH:00000003 [INF] User logged in. (fdce0db4)
2022-02-17T13:39:28.8153749+07:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2022-02-17T13:39:28.8234086+07:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2022-02-17T13:39:28.8249726+07:00  [INF] Hosting environment: "Development" (c3307c92)
2022-02-17T13:39:28.8262433+07:00  [INF] Content root path: "E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC" (b5d60022)
2022-02-17T13:39:30.1482995+07:00 0HMFHS0VP7U95:00000001 [WRN] Failed to determine the https port for redirect. (ca76cc21)
2022-02-17T13:39:35.1383307+07:00 0HMFHS0VP7U99:00000004 [INF] User logged in. (fdce0db4)
2022-02-17T13:40:37.6887999+07:00 0HMFHS0VP7U95:0000001B [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Reverse[TSource](IEnumerable`1 source)
   at AspNetCore.Areas_Admin_Views_NhanVien__profileContractInfoPartial.<>c.<ExecuteAsync>b__16_0(HopDongViewModel x) in E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC\Areas\Admin\Views\NhanVien\_profileContractInfoPartial.cshtml:line 9
   at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
   at System.Linq.EnumerableSorter`1.ComputeMap(TElement[] elements, Int32 count)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.GetEnumerator()+MoveNext()
   at AspNetCore.Areas_Admin_Views_NhanVien__profileContractInfoPartial.ExecuteAsync() in E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC\Areas\Admin\Views\NhanVien\_profileContractInfoPartial.cshtml:line 9
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.PartialViewResultExecutor.ExecuteAsync(ActionContext context, PartialViewResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2022-02-17T13:41:11.3450505+07:00 0HMFHS0VP7U95:0000001E [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.InvalidOperationException: Failed to compare two elements in the array.
 ---> System.ArgumentException: At least one object must implement IComparable.
   at System.Collections.Comparer.Compare(Object a, Object b)
   at System.Collections.Generic.ObjectComparer`1.Compare(T x, T y)
   at System.Linq.EnumerableSorter`2.CompareAnyKeys(Int32 index1, Int32 index2)
   at System.Collections.Generic.ComparisonComparer`1.Compare(T x, T y)
   at System.Collections.Generic.ArraySortHelper`1.SwapIfGreater(T[] keys, Comparison`1 comparer, Int32 a, Int32 b)
   at System.Collections.Generic.ArraySortHelper`1.IntroSort(T[] keys, Int32 lo, Int32 hi, Int32 depthLimit, Comparison`1 comparer)
   at System.Collections.Generic.GenericArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   --- End of inner exception stack trace ---
   at System.Collections.Generic.GenericArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Linq.EnumerableSorter`2.QuickSort(Int32[] keys, Int32 lo, Int32 hi)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.GetEnumerator()+MoveNext()
   at AspNetCore.Areas_Admin_Views_NhanVien__profileContractInfoPartial.ExecuteAsync() in E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC\Areas\Admin\Views\NhanVien\_profileContractInfoPartial.cshtml:line 9
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper.RenderPartialCoreAsync(String partialViewName, Object model, ViewDataDictionary viewData, TextWriter writer)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper.PartialAsync(String partialViewName, Object model, ViewDataDictionary viewData)
   at AspNetCore.Areas_Admin_Views_NhanVien_Profile.ExecuteAsync() in E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC\Areas\Admin\Views\NhanVien\Profile.cshtml:line 226
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2022-02-17T13:43:05.4366034+07:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2022-02-17T13:43:05.4447505+07:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2022-02-17T13:43:05.4461768+07:00  [INF] Hosting environment: "Development" (c3307c92)
2022-02-17T13:43:05.4475574+07:00  [INF] Content root path: "E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC" (b5d60022)
2022-02-17T13:43:06.7549800+07:00 0HMFHS30BMA8V:00000001 [WRN] Failed to determine the https port for redirect. (ca76cc21)
2022-02-17T13:43:18.5494017+07:00 0HMFHS30BMA92:00000005 [INF] User logged in. (fdce0db4)
2022-02-17T13:47:37.9291524+07:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2022-02-17T13:47:37.9449678+07:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2022-02-17T13:47:37.9474217+07:00  [INF] Hosting environment: "Development" (c3307c92)
2022-02-17T13:47:37.9492630+07:00  [INF] Content root path: "E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC" (b5d60022)
2022-02-17T13:47:39.1951868+07:00 0HMFHS5HHR6T8:00000001 [WRN] Failed to determine the https port for redirect. (ca76cc21)
2022-02-17T13:47:48.6707943+07:00 0HMFHS5HHR6TA:00000004 [INF] User logged in. (fdce0db4)
2022-02-17T13:55:49.2502655+07:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2022-02-17T13:55:49.2582890+07:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2022-02-17T13:55:49.2597911+07:00  [INF] Hosting environment: "Development" (c3307c92)
2022-02-17T13:55:49.2610594+07:00  [INF] Content root path: "E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC" (b5d60022)
2022-02-17T13:55:50.2950232+07:00 0HMFHSA3T5NKF:00000001 [WRN] Failed to determine the https port for redirect. (ca76cc21)
2022-02-17T13:55:54.4048412+07:00 0HMFHSA3T5NKF:00000006 [INF] User logged in. (fdce0db4)
2022-02-17T14:50:18.2055716+07:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2022-02-17T14:50:18.2137219+07:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2022-02-17T14:50:18.2153722+07:00  [INF] Hosting environment: "Development" (c3307c92)
2022-02-17T14:50:18.2170360+07:00  [INF] Content root path: "E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC" (b5d60022)
2022-02-17T14:50:19.1231470+07:00 0HMFHT8I3TVUC:00000001 [WRN] Failed to determine the https port for redirect. (ca76cc21)
2022-02-17T14:50:24.7774867+07:00 0HMFHT8I3TVUE:00000005 [INF] User logged in. (fdce0db4)
2022-02-17T14:56:36.3794750+07:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2022-02-17T14:56:36.3870125+07:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2022-02-17T14:56:36.3884677+07:00  [INF] Hosting environment: "Development" (c3307c92)
2022-02-17T14:56:36.3898900+07:00  [INF] Content root path: "E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC" (b5d60022)
2022-02-17T14:56:37.8286105+07:00 0HMFHTC2TU0MM:00000001 [WRN] Failed to determine the https port for redirect. (ca76cc21)
2022-02-17T14:56:42.1168288+07:00 0HMFHTC2TU0MP:00000004 [INF] User logged in. (fdce0db4)
2022-02-17T15:02:22.0798915+07:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2022-02-17T15:02:22.0877390+07:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2022-02-17T15:02:22.0897021+07:00  [INF] Hosting environment: "Development" (c3307c92)
2022-02-17T15:02:22.0911798+07:00  [INF] Content root path: "E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC" (b5d60022)
2022-02-17T15:02:23.1933657+07:00 0HMFHTF9TM51G:00000001 [WRN] Failed to determine the https port for redirect. (ca76cc21)
2022-02-17T15:02:27.6847057+07:00 0HMFHTF9TM51I:00000003 [INF] User logged in. (fdce0db4)
2022-02-17T15:20:10.1099479+07:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2022-02-17T15:20:10.1178747+07:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2022-02-17T15:20:10.1193837+07:00  [INF] Hosting environment: "Development" (c3307c92)
2022-02-17T15:20:10.1206517+07:00  [INF] Content root path: "E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC" (b5d60022)
2022-02-17T15:20:11.3335649+07:00 0HMFHTP84U8OI:00000001 [WRN] Failed to determine the https port for redirect. (ca76cc21)
2022-02-17T15:20:15.4225023+07:00 0HMFHTP84U8OJ:00000005 [INF] User logged in. (fdce0db4)
2022-02-17T15:21:38.9915159+07:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2022-02-17T15:21:38.9987826+07:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2022-02-17T15:21:39.0002770+07:00  [INF] Hosting environment: "Development" (c3307c92)
2022-02-17T15:21:39.0015217+07:00  [INF] Content root path: "E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC" (b5d60022)
2022-02-17T15:21:40.2531217+07:00 0HMFHTQ2NK3SF:00000001 [WRN] Failed to determine the https port for redirect. (ca76cc21)
2022-02-17T15:21:44.6378488+07:00 0HMFHTQ2NK3SJ:00000004 [INF] User logged in. (fdce0db4)
2022-02-17T16:06:02.3447102+07:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2022-02-17T16:06:02.3524092+07:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2022-02-17T16:06:02.3539866+07:00  [INF] Hosting environment: "Development" (c3307c92)
2022-02-17T16:06:02.3807407+07:00  [INF] Content root path: "E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC" (b5d60022)
2022-02-17T16:06:03.4598330+07:00 0HMFHUISDHNUO:00000001 [WRN] Failed to determine the https port for redirect. (ca76cc21)
2022-02-17T16:06:08.0783571+07:00 0HMFHUISDHNUR:00000004 [INF] User logged in. (fdce0db4)
2022-02-17T16:33:46.8001162+07:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2022-02-17T16:33:46.8085407+07:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2022-02-17T16:33:46.8109491+07:00  [INF] Hosting environment: "Development" (c3307c92)
2022-02-17T16:33:46.8448513+07:00  [INF] Content root path: "E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC" (b5d60022)
2022-02-17T16:33:48.1969500+07:00 0HMFHV2CHGOS4:00000001 [WRN] Failed to determine the https port for redirect. (ca76cc21)
2022-02-17T16:33:52.8366658+07:00 0HMFHV2CHGOS4:00000006 [INF] User logged in. (fdce0db4)
2022-02-17T16:34:39.5613713+07:00 0HMFHV2CHGOS8:00000014 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Number.ParseInt32(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
   at System.Int32.Parse(String s)
   at VOC.Application.Implementation.NhanVienService.ImportExcel(String filePath) in E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC.Application\Implementation\NhanVienService.cs:line 212
   at VOC.Areas.Admin.Controllers.NhanVienController.ImportExcel(IList`1 files) in E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC\Areas\Admin\Controllers\NhanVienController.cs:line 151
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2022-02-17T16:35:12.0605281+07:00 0HMFHV2CHGOS5:00000017 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Number.ParseInt32(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
   at System.Int32.Parse(String s)
   at VOC.Application.Implementation.NhanVienService.ImportExcel(String filePath) in E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC.Application\Implementation\NhanVienService.cs:line 212
   at VOC.Areas.Admin.Controllers.NhanVienController.ImportExcel(IList`1 files) in E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC\Areas\Admin\Controllers\NhanVienController.cs:line 151
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2022-02-17T16:36:04.3199308+07:00 0HMFHV2CHGOS5:00000018 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Number.ParseInt32(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
   at System.Int32.Parse(String s)
   at VOC.Application.Implementation.NhanVienService.ImportExcel(String filePath) in E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC.Application\Implementation\NhanVienService.cs:line 212
   at VOC.Areas.Admin.Controllers.NhanVienController.ImportExcel(IList`1 files) in E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC\Areas\Admin\Controllers\NhanVienController.cs:line 151
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2022-02-17T16:36:48.0646029+07:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2022-02-17T16:36:48.0722416+07:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2022-02-17T16:36:48.0737040+07:00  [INF] Hosting environment: "Development" (c3307c92)
2022-02-17T16:36:48.0750465+07:00  [INF] Content root path: "E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC" (b5d60022)
2022-02-17T16:36:49.6329089+07:00 0HMFHV42IC3TH:00000001 [WRN] Failed to determine the https port for redirect. (ca76cc21)
2022-02-17T16:36:54.0324710+07:00 0HMFHV42IC3TI:00000004 [INF] User logged in. (fdce0db4)
2022-02-17T16:44:00.8453386+07:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2022-02-17T16:44:00.8530241+07:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2022-02-17T16:44:00.8548202+07:00  [INF] Hosting environment: "Development" (c3307c92)
2022-02-17T16:44:00.8561176+07:00  [INF] Content root path: "E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC" (b5d60022)
2022-02-17T16:44:01.9271303+07:00 0HMFHV83EA0J9:00000001 [WRN] Failed to determine the https port for redirect. (ca76cc21)
2022-02-17T16:44:07.3277601+07:00 0HMFHV83EA0JD:00000004 [INF] User logged in. (fdce0db4)
2022-02-17T16:44:49.8139063+07:00 0HMFHV83EA0JB:00000018 [ERR] Failed executing DbCommand ("101"ms) [Parameters=["@p0='?' (Size = 50), @p1='?' (Size = 50), @p2='?' (Size = 50), @p3='?' (Size = 50), @p4='?' (Size = 50), @p5='?' (Size = 50), @p6='?' (Size = 50), @p7='?' (Size = 50)"], CommandType='Text', CommandTimeout='30']"
""SET NOCOUNT ON;
INSERT INTO [HR_BHXH] ([Id], [DateCreated], [DateModified], [MaNV], [NgayKetThuc], [NgayThamGia], [UserCreated], [UserModified])
VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6, @p7);" (627a98df)
2022-02-17T16:44:49.9385251+07:00 0HMFHV83EA0JB:00000018 [ERR] An exception occurred in the database while saving changes for context type '"VOC.Data.EF.AppDBContext"'."
""Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Violation of PRIMARY KEY constraint 'PK_HR_BHXH'. Cannot insert duplicate key in object 'dbo.HR_BHXH'. The duplicate key value is (123123123123).
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
ClientConnectionId:5ae00b53-d72a-4835-b570-bdbf2d44d38e
Error Number:2627,State:1,Class:14
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(DbContext _, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)" (170f029e)
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Violation of PRIMARY KEY constraint 'PK_HR_BHXH'. Cannot insert duplicate key in object 'dbo.HR_BHXH'. The duplicate key value is (123123123123).
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
ClientConnectionId:5ae00b53-d72a-4835-b570-bdbf2d44d38e
Error Number:2627,State:1,Class:14
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(DbContext _, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
2022-02-17T16:44:50.3236322+07:00 0HMFHV83EA0JB:00000018 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Violation of PRIMARY KEY constraint 'PK_HR_BHXH'. Cannot insert duplicate key in object 'dbo.HR_BHXH'. The duplicate key value is (123123123123).
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
ClientConnectionId:5ae00b53-d72a-4835-b570-bdbf2d44d38e
Error Number:2627,State:1,Class:14
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(DbContext _, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at VOC.Data.EF.AppDBContext.SaveChanges() in E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC.Data.EF\AppDBContext.cs:line 92
   at VOC.Data.EF.EFUnitOfWork.Commit() in E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC.Data.EF\EFUnitOfWork.cs:line 17
   at VOC.Application.Implementation.NhanVienService.Save() in E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC.Application\Implementation\NhanVienService.cs:line 84
   at VOC.Areas.Admin.Controllers.NhanVienController.ImportExcel(IList`1 files) in E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC\Areas\Admin\Controllers\NhanVienController.cs:line 152
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2022-02-17T16:46:05.1818384+07:00 0HMFHV83EA0JB:00000019 [ERR] Failed executing DbCommand ("117"ms) [Parameters=["@p0='?' (Size = 50), @p1='?' (Size = 50), @p2='?' (Size = 50), @p3='?' (Size = 50), @p4='?' (Size = 50), @p5='?' (Size = 50), @p6='?' (Size = 50), @p7='?' (Size = 50)"], CommandType='Text', CommandTimeout='30']"
""SET NOCOUNT ON;
INSERT INTO [HR_BHXH] ([Id], [DateCreated], [DateModified], [MaNV], [NgayKetThuc], [NgayThamGia], [UserCreated], [UserModified])
VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6, @p7);" (627a98df)
2022-02-17T16:46:05.2622930+07:00 0HMFHV83EA0JB:00000019 [ERR] An exception occurred in the database while saving changes for context type '"VOC.Data.EF.AppDBContext"'."
""Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Violation of PRIMARY KEY constraint 'PK_HR_BHXH'. Cannot insert duplicate key in object 'dbo.HR_BHXH'. The duplicate key value is (123123123123).
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
ClientConnectionId:5ae00b53-d72a-4835-b570-bdbf2d44d38e
Error Number:2627,State:1,Class:14
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(DbContext _, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)" (170f029e)
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Violation of PRIMARY KEY constraint 'PK_HR_BHXH'. Cannot insert duplicate key in object 'dbo.HR_BHXH'. The duplicate key value is (123123123123).
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
ClientConnectionId:5ae00b53-d72a-4835-b570-bdbf2d44d38e
Error Number:2627,State:1,Class:14
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(DbContext _, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at VOC.Data.EF.AppDBContext.SaveChanges() in E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC.Data.EF\AppDBContext.cs:line 92
2022-02-17T16:46:05.7245798+07:00 0HMFHV83EA0JB:00000019 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Violation of PRIMARY KEY constraint 'PK_HR_BHXH'. Cannot insert duplicate key in object 'dbo.HR_BHXH'. The duplicate key value is (123123123123).
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
ClientConnectionId:5ae00b53-d72a-4835-b570-bdbf2d44d38e
Error Number:2627,State:1,Class:14
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(DbContext _, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at VOC.Data.EF.AppDBContext.SaveChanges() in E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC.Data.EF\AppDBContext.cs:line 92
   at VOC.Data.EF.EFUnitOfWork.Commit() in E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC.Data.EF\EFUnitOfWork.cs:line 17
   at VOC.Application.Implementation.NhanVienService.Save() in E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC.Application\Implementation\NhanVienService.cs:line 84
   at VOC.Areas.Admin.Controllers.NhanVienController.ImportExcel(IList`1 files) in E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC\Areas\Admin\Controllers\NhanVienController.cs:line 152
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2022-02-17T16:49:02.0781897+07:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2022-02-17T16:49:02.0900480+07:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2022-02-17T16:49:02.0917004+07:00  [INF] Hosting environment: "Development" (c3307c92)
2022-02-17T16:49:02.0931061+07:00  [INF] Content root path: "E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC" (b5d60022)
2022-02-17T16:49:03.3829731+07:00 0HMFHVAT867FO:00000001 [WRN] Failed to determine the https port for redirect. (ca76cc21)
2022-02-17T16:49:08.0629611+07:00 0HMFHVAT867FS:00000004 [INF] User logged in. (fdce0db4)
2022-02-17T17:07:42.6578819+07:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2022-02-17T17:07:42.6656255+07:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2022-02-17T17:07:42.6671541+07:00  [INF] Hosting environment: "Development" (c3307c92)
2022-02-17T17:07:42.6683749+07:00  [INF] Content root path: "E:\WorkSpace\Source\NET CORE\ASP.NET CORE\VOC\VOC" (b5d60022)
2022-02-17T17:07:43.8435322+07:00 0HMFHVLB7F36E:00000001 [WRN] Failed to determine the https port for redirect. (ca76cc21)
2022-02-17T17:07:49.5955751+07:00 0HMFHVLB7F36H:00000004 [INF] User logged in. (fdce0db4)
